Utils = require 'Utils'

module.exports =
  actions: Utils.keyMirror
    ADD_ANSWERS: null
    ADD_CATEGORIES: null
    ADD_QUESTION: null
    AUTH: null
    BADGES_VIEWED: null
    CARD_COMMENT: null
    CARD_SELECT: null
    FILTER_PREFS: null
    LOADING_DONE: null
    LOADING_START: null
    LOAD_ACTIVITY: null
    LOAD_APP: null
    LOAD_CARD: null
    LOAD_CATEGORIES: null
    LOAD_LINK: null
    LOGIN: null
    LOGOUT: null
    MENU_SELECT: null
    NEXT_PAGE: null
    PEGG_SUBMIT: null
    PICK_MOOD: null
    PLAY_CONTINUE: null
    PLUG_IMAGE: null
    PREF_SUBMIT: null
    PREV_PAGE: null
    SHOW_MESSAGE: null
    SINGLE_CARD_CARD_COMMENT: null
    SINGLE_CARD_LOAD: null
    SINGLE_CARD_NEXT_PAGE: null
    SINGLE_CARD_PEGG_SUBMIT: null
    SINGLE_CARD_PLUG_IMAGE: null
    SINGLE_CARD_PREF_SUBMIT: null
    SINGLE_CARD_PREV_PAGE: null
    SUBSCRIBER_SUBMIT: null
    USER_LOAD: null
    USER_LOGIN: null
    USER_LOGOUT: null

  stores: Utils.keyMirror
    # Generic
    CHANGE: null

    # Specific
    ACTIVITY_CHANGE: null
    CARDS_CHANGE: null
    CARD_CHANGE: null
    CARD_FAIL: null
    CARD_WIN: null
    CATEGORIES_CHANGE: null
    CHOICES_CHANGE: null
    COMMENTS_CHANGE: null
    HIDE_MESSAGE: null
    LOAD_ERROR: null
    LOGIN_CHANGE: null
    MENU_CHANGE: null
    MOOD_CHANGE: null
    MOODS_LOADED: null
    NO_PEGGS_REMAINING: null
    NO_PREFS_REMAINING: null
    PAGE_CHANGE: null
    PLAY_CHANGE: null
    PLAY_PEGGS: null
    PLAY_PREFS: null
    PLUG_SAVED: null
    PREF_IMAGES_CHANGE: null
    PREF_SAVED: null
    PROFILE_ACTIVITY_CHANGE: null
    PROFILE_LOAD: null
    REQUIRE_LOGIN: null
    SHOW_MESSAGE: null
    STATUS_CHANGE: null
    SUBSCRIBE_FAIL: null
    SUBSCRIBE_PASS: null
    UNLOCK_ACHIEVED: null
    BADGE_CHANGE: null
    GAME_LOADED: null
